# Generated by Django 6.0.8 on 2026-08-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbarticle',
            name='author',
        ),
        migrations.RemoveConstraint(
            model_name='kbarticleversion',
            name='unique_article_version',
        ),
        migrations.RemoveConstraint(
            model_name='ticketkblink',
            name='unique_ticket_article_link',
        ),
        migrations.RemoveField(
            model_name='ticketkblink',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ticketkblink',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='ticketkblink',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='KBArticleVersion',
        ),
        migrations.DeleteModel(
            name='KBArticle',
        ),
        migrations.DeleteModel(
            name='TicketKBLink',
        ),
    ]
